apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: '1.0'
  name: ulian-job-5657
spec:
  autoscalerOptions:
    idleTimeoutSeconds: 60
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
    upscalingMode: Default
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      block: 'true'
      dashboard-host: 0.0.0.0
    serviceType: NodePort
    template:
      spec:
        containers:
        - image: wajc.zhejianglab.com/wasc/torch:1.12.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            limits:
              cpu: 4
              memory: 8Gi
            requests:
              cpu: 4
              memory: 8Gi
  rayVersion: 2.0.0
  workerGroupSpecs:
  - groupName: group
    maxReplicas: 3
    minReplicas: 3
    rayStartParams:
      block: 'true'
    replicas: 3
    template:
      metadata:
        annotations:
          key: value
        labels:
          key: value
      spec:
        containers:
        - image: wajc.zhejianglab.com/wasc/torch:1.12.0
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - ray stop
          name: machine-learning
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 2
              memory: 4Gi
        initContainers:
        - command:
          - sh
          - -c
          - until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
            do echo waiting for myservice; sleep 2; done
          image: wajc.zhejianglab.com/base/busybox:1.28
          name: init-myservice
